name: Invoke Lambda Function

on:
  push:
    branches:
      - main

jobs:
  invoke_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      # Codificar el payload en base64
      - name: Base64 encode payload
        id: encode
        run: |
          PAYLOAD='{"message": "Nuevo commit en la rama main"}'
          ENCODED_PAYLOAD=$(echo -n "$PAYLOAD" | base64)
          echo "::set-output name=encoded_payload::$ENCODED_PAYLOAD"

      # Invocar la Lambda con el payload codificado en base64
      - name: Invoke Lambda Function
        run: |
          aws lambda invoke \
            --function-name NotificacionCommit-Push \
            --payload "${{ steps.encode.outputs.encoded_payload }}" \
            response.json

      # Se muestra la respuesta de la invocación
      - name: Output Lambda response
        run: cat response.json
