name: Invoke Lambda Function

# Cuando haya un commit en la rama 'main' se ejecutará automáticamente este flujo,
# invokando a la función lambda de AWS para notificar el evento
on:
  push:
    branches:
      - main

jobs:
  invoke_lambda:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

      # Credenciales de AWS y secrets
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-secret-access-token: ${{ secrets.AWS_SECRET_ACCESS_TOKEN }}
          region: 'us-east-1' 

      # Se invoca la función Lambda
      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name NotificacionEventoPush  # Nombre de tu función Lambda tal como se definió en AWS
            --payload '{"message": "Nuevo commit en la rama main"}'  
            response.json

      # Se muestra la respuesta de la invocación
      - name: Output Lambda response
        run: cat response.json
