name: Invoke Lambda Function

on:
  push:
    branches:
      - main

jobs:
  invoke_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: 'us-east-1'

      # Aquí ya no es necesario codificar en base64, directamente pasamos el payload
      - name: NotificacionCommit-Push
        run: |
          aws lambda invoke \
            --function-name NotificacionCommit-Push \
            --payload '{"message": "Nuevo commit en la rama main"}' \
            response.json

      # Se muestra la respuesta de la invocación
      - name: Output Lambda response
        run: |
          cat response.json
